In [2]:
import numpy as np


In [5]:
tr = np.random.rand(100, 7)
tst = np.random.rand(100, 3)
print(f'test size - {tst.shape} \ntrain size - {tr.shape}')

test size - (100, 3) 
train size - (100, 7)


In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
tr.transpose().shape

(7, 100)

In [9]:
np.sum(tr), np.sum(tst)

(np.float64(344.8980060517457), np.float64(153.5975644125223))

In [10]:
np.mean(tr)

np.float64(0.49271143721677957)

In [11]:
x = np.hstack((tr, tst))
x.shape

(100, 10)

In [13]:
x[0:5, :3]

array([[0.94497834, 0.61103594, 0.52216336],
       [0.89945599, 0.00947018, 0.3758304 ],
       [0.47783308, 0.65299325, 0.83206788],
       [0.39498173, 0.68540703, 0.07993526],
       [0.39173183, 0.93505662, 0.33219728]])

In [16]:
dispr = np.var(x, axis=0)
dispr

array([0.08242456, 0.07548492, 0.07803267, 0.07324177, 0.07780549,
       0.08400311, 0.08419924, 0.07562959, 0.06976733, 0.07434786])